[package]
name = "arch-ops"
version = "0.1.0"
authors = ["chorm"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.6.1"

[features]
x86 = []
arm = []
aarch64 = []
wc65c816 = []
riscv = []
propeller = []
propeller2 = []
default-archs = ["x86","arm","aarch64","wc65c816","riscv","propeller","propeller2"]
default = ["default-archs"]
all-archs = ["default-archs"]
all = ["all-archs"]