name: Rust

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rust:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust-channel: [nightly]

    steps:
      - uses: actions/checkout@v2
      - name: Install Rustup Toolchain
        run: |
          rustup toolchain add ${{ matrix.rust-channel }}
          rustup default ${{ matrix.rust-channel }}
          rustup update
          rustup component add clippy
      - name: Build
        run: |
           cargo clippy --all-features
