name: Rust

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rust:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        rust-channel: [1.56.0, stable, beta,nightly]
        exclude:
          - os: [windows-latest, macos-latest]
            rust-channel: [beta, nightly]

    steps:
      - uses: actions/checkout@v2
      - name: Install Rustup Toolchain
        run: |
          rustup toolchain add ${{ matrix.rust-channel }}
          rustup default ${{ matrix.rust-channel }}
          rustup update
          rustup component add clippy
      - name: Build
        run: |
           cargo build --all-features
           cargo test --all-features
           cargo clippy --all-features
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo fmt -- --check  
